import { sansLight, sansRegular, sansMedium, sansBold, yekanBlack } from "@/constant/Fonts";
import "./globals.css";
import MainLayout from "@/components/MainLayout";


export const metadata = {
  title: "چتیفای - چت روم فارسی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={
          `${sansRegular.className} ${sansLight.variable} ${sansRegular.variable} ${sansMedium.variable} ${sansBold.variable} ${yekanBlack.variable}`
        }
      >

        <MainLayout>
          {children}
        </MainLayout>

      </body>
    </html>
  );
}
